all:
  hosts:
    ansible-client1:
      ansible_host: 100.0.0.20
      ansible_port: 22
      ansible_user: nchuong
      ansible_ssh_private_key_file: /home/nchuong/.ssh/id_rsa
    ansible-client2:
      ansible_host: 100.0.0.30
      ansible_port: 22
      ansible_user: nchuong
      ansible_ssh_private_key_file: /home/nchuong/.ssh/id_rsa
  children:
    web:
      hosts:
        ansible-client1:  
    db:
      hosts:
        ansible-client2: