all:
  hosts:
    ansible1: 
      ansible_host: 100.0.0.20
      ansible_port: 22
      ansible_user: nchuong
      ansible_ssh_private_key_file: /home/nchuong/.ssh/id_rsa
    ansible2:
      ansible_host: 100.0.0.30
      ansible_port: 22
      ansible_user: nchuong
      ansible_ssh_private_key_file: /home/nchuong/.ssh/id_rsa
  children:
    web:
      hosts:
        ansible1:  
    db:
      hosts:
        ansible2:
  