- hosts: localhost
  tasks:
  - name: Display port
    debug: #debug moudle de display bien ra
      msg: "{{ http_port }}"
  - name: Display name of server
    debug: #debug moudle de display bien ra
      msg: "{{ server_name }}"

       